version: '3.8'

services:
  db:
    image: timescale/timescaledb-ha:pg16
    container_name: hdd-nexus-db
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: hdd_nexus
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/home/postgres/pgdata/data

volumes:
  postgres_data:
